#!/bin/sh
mvn clean package && docker build -t muzammilnagariya/CabApp .
docker rm -f CabApp 2>/dev/null || true && docker run -it --name CabApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name CabApp muzammilnagariya/CabApp
